[redhat] redhat/Makefile: Check for RH_KABI usage in uapi directories
Message-id: <20200226162639.12935-1-prarit@redhat.com>
Patchwork-id: 295349
Patchwork-instance: patchwork
O-Subject: [RHEL8.2 BZ 1806602 v3] redhat/Makefile: Check for RH_KABI usage in uapi directories
Bugzilla: 1806602
RH-Acked-by: Bruno Meneguele <bmeneg@redhat.com>
RH-Acked-by: Luis Goncalves <lgoncalv@redhat.com>
RH-Acked-by: Jarod Wilson <jarod@redhat.com>
RH-Acked-by: Jiri Benc <jbenc@redhat.com>

Bugzilla: http://bugzilla.redhat.com/1806602
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=26792905
Local Tree: git://git.engineering.redhat.com/users/prarit/rhel8 1806602_v3

RH_KABI macros cannot be used in uapi directories.

Add a simple find & grep for RH_KABI in uapi directories.

Testing: Tested with & without a RH_KABI patch in
arch/x86/include/uapi/asm.  Adds about 0.1 seconds to build time.

Before the patch:
[08:25 AM root@dell-pem830-01 rhel]# time make rh-check-kabi
make -C redhat rh-check-kabi
make[1]: Entering directory '/home/rhel/redhat'
BUILDID is ".test".
make[1]: Leaving directory '/home/rhel/redhat'

real	0m0.891s
user	0m0.726s
sys	0m0.165s

After the patch:
[08:25 AM root@dell-pem830-01 rhel]# time make rh-check-kabi
make -C redhat rh-check-kabi
make[1]: Entering directory '/home/rhel/redhat'
BUILDID is ".test".
make[1]: Leaving directory '/home/rhel/redhat'

real	0m0.925s
user	0m0.732s
sys	0m0.200s

Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Cc: Jiri Benc <jbenc@redhat.com>

Cc: Denys Vlasenko <dvlasenk@redhat.com>
Cc: Augusto Caringi <acaringi@redhat.com>
Cc: Luis Claudio Goncalves <lgoncalv@redhat.com>
Cc: Rado Vrbovsky <rvrbovsk@redhat.com>
Cc: "Herton R. Krzesinski" <herton@redhat.com>
Cc: Frantisek Hrbata <fhrbata@redhat.com>
Cc: Juri Lelli <jlelli@redhat.com>
Cc: Clark Williams <williams@redhat.com>
Cc: Bruno Meneguele <bmeneg@redhat.com>
Cc: Jan Stancek <jstancek@redhat.com>
Cc: Laura Abbott <labbott@redhat.com>
Cc: Jeremy Cline <jcline@redhat.com>
Signed-off-by: Frantisek Hrbata <fhrbata@redhat.com>

diff --git a/redhat/Makefile b/redhat/Makefile
--- a/redhat/Makefile
+++ b/redhat/Makefile
@@ -93,6 +93,10 @@ rh-check-kabi: rh-kabi
 		echo "ERROR: You must compile the kernel and modules first";\
 		exit 1;\
 	fi
+	@if grep -n -r RH_KABI ../include/uapi ../arch/*/include/uapi; then \
+		echo "ERROR: RH_KABI macros cannot be used in uapi directories."; \
+		exit 1; \
+	fi
 	@$(REDHAT)/kabi/check-kabi -k $(REDHAT)/kabi/Module.kabi_$(MACH) \
 	 -s $(_OUTPUT)/Module.symvers
 
