[redhat] kabi: integrate kabi-dw
Message-id: <20181105091440.16687-1-jmarchan@redhat.com>
Patchwork-id: 9317
O-Subject: [kernel team] [RHEL8 PATCH V4] kabi: integrate kabi-dw
Bugzilla: 1569101
RH-Acked-by: Yauheni Kaliuta <yauheni.kaliuta@redhat.com>
RH-Acked-by: Rafael Aquini <aquini@redhat.com>

Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1569101
Brew build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=19040764
Upstream status: RHEL-only
Changes V3-V4:
- remove useless empty line
- replace "running" by "building" in doc
Changes V2->V3:
- disable kabidwchk for gcov build or if kabichk is disabled
- update doc to use BUILDOPTS
Changes V1->V2:
- rebase on 4.18.0-33.el8
- uses plain sh funtions in run_kabi-dw.sh as suggested by Yauheni

This patch integrates the kabi-dw tool into the kernel tree. There are two
intended ways to use the tool:

1) As a kernel developer running a local quick build you do:

$ make && make modules
$ make rh-kabi-dw-base  # To create the baseline kABI dataset
$ <apply your patch here>
$ make && make modules
$ make rh-kabi-dw-check # To generate a new dataset and compare it with the
                        # one stored previously

2) As a kernel maintainer preparing official build you generate the baseline
dataset for all arches by building with BUILDOPTS="+kabidw_base", e.g.:

make rh-brew BUILDOPTS="+kabidw_base"

Then you run a (scratch) brew build which will generate following sub-package
for all supported arches:

kernel-kabidw-base

The package contains the baseline dataset generated for all supported arches. If
the content of these subpackages is copied from /kabidw-base directory into the
redhat/kabi-dwarf/base directory of the kernel tree the following brew builds
will issue the comparison of the build with the baseline dataset. The report in
the brew build.log looks like this:

**** kABI DWARF-based comparison report ****
+ /builddir/build/BUILDROOT/kernel-3.10.0-681.el7.test.x86_64/kabi-dwarf/run_kabi-dw.sh compare /builddir/build/BUILDROOT/kernel-3.10.0-681.el7.test.x86_64/kabi-dwarf/base/x86_64 /builddir/build/BUILDROOT/kernel-3.10.0-681.el7.test.x86_64/kabi-dwarf/base/x86_64.tmp
Changes detected in: struct--pacct_struct.txt
Added:
+0x38 int this_is_newly_add_field_for_testing;
**** End of kABI DWARF-based comparison report ****

Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

diff --git a/redhat/Makefile b/redhat/Makefile
--- a/redhat/Makefile
+++ b/redhat/Makefile
@@ -38,8 +38,11 @@ ifeq ("$(origin O)", "command line")
   _EXTRA_ARGS := O=$(_OUTPUT)
 endif
 
+CURARCH := $(shell uname -m)
 ARCHCONFIG := $(shell uname -m | sed -e s/x86_64/X86_64/ \
 				     -e s/s390x/S390/ -e s/ppc.*/PPC/ )
+
+KABIDW := $(REDHAT)/kabi-dwarf
 
 include Makefile.cross
 
@@ -95,6 +98,30 @@ rh-check-kabi-dup: rh-kabi-dup
 	@$(REDHAT)/kabi/check-kabi -k $(REDHAT)/kabi/Module.kabi_dup_$(MACH) \
 	-s $(_OUTPUT)/Module.symvers
 
+rh-kabi-dw-base: rh-kabi
+	@echo "Generating baseline dataset for KABI DWARF-based comparison..."
+	@echo "**** GENERATING DWARF-based kABI baseline dataset ****"
+	@$(KABIDW)/run_kabi-dw.sh generate \
+		$(REDHAT)/kabi/kabi-current/kabi_whitelist_$(CURARCH) \
+		$(_OUTPUT) $(KABIDW)/base/$(CURARCH)/
+
+rh-kabi-dw-check: rh-kabi
+	@if [ ! -d $(KABIDW)/base/$(CURARCH) ]; then \
+		echo "**** ERROR: ****"; \
+		echo "Comparison base not found in $(KABIDW)/base/$(CURARCH)."; \
+		echo "Please run \"make rh-kabi-dw-base\" first!"; \
+		exit 1; \
+	fi
+	@echo "**** GENERATING DWARF-based kABI dataset ****"
+	@$(KABIDW)/run_kabi-dw.sh generate \
+		$(REDHAT)/kabi/kabi-current/kabi_whitelist_$(CURARCH) \
+		$(_OUTPUT) $(KABIDW)/base/$(CURARCH).tmp/
+	@echo "**** KABI DWARF-based comparison report ****"
+	@$(KABIDW)/run_kabi-dw.sh compare \
+		$(KABIDW)/base/$(CURARCH) $(KABIDW)/base/$(CURARCH).tmp || :
+	@echo "**** End of KABI DWARF-based comparison report ****"
+	@rm -rf $(KABIDW)/base/$(CURARCH).tmp
+
 rh-configs: rh-configs-prep
 	@cd $(REDHAT)/configs; VERSION=$(KVERSION) ./generate_all_configs.sh; \
 	./process_configs.sh -w $(PACKAGE_NAME) $(KVERSION)
@@ -141,6 +168,13 @@ $(TARBALL):
 $(KABI_TARBALL):
 	@(cd kabi && tar cjvf $(SOURCES)/$(KABI_TARFILE) kabi-rhel$(RHELMAJOR)* kabi-current)
 
+.PHONY: $(KABIDW_TARBALL)
+$(KABIDW_TARBALL):
+	@if [ ! -d $(KABIDW)/base ]; then \
+		mkdir -p $(KABIDW)/base; \
+	fi
+	@(cd kabi-dwarf && tar cjvf $(SOURCES)/$(KABIDW_TARFILE) base run_kabi-dw.sh)
+
 setup-source: rh-clean-sources
 	@cp $(REDHAT)/$(SPECFILE).template $(SOURCES)/$(SPECFILE)
 	@$(REDHAT)/genspec.sh $(SOURCES) $(SOURCES)/$(SPECFILE) $(PKGRELEASE) $(RPMKVERSION) $(RPMKPATCHLEVEL) $(RPMKSUBLEVEL) $(DISTRO_BUILD) $(RELEASED_KERNEL) $(SPECRELEASE) $(__ZSTREAM) "$(BUILDOPTS)" $(MARKER)
@@ -168,6 +202,10 @@ sources-rh: $(TARBALL)
 		cp kabi/Module.kabi_dup_$$KABIARCH $(SOURCES)/; \
 	done
 	@(cd kabi && tar cjvf $(SOURCES)/$(KABI_TARFILE) kabi-rhel$(RHELMAJOR)* kabi-current)
+	@if [ ! -d $(KABIDW)/base ]; then \
+		mkdir -p $(KABIDW)/base; \
+	fi
+	@(cd kabi-dwarf && tar cjvf $(SOURCES)/$(KABIDW_TARFILE) base run_kabi-dw.sh)
 
 rh-sources: setup-source rh-configs-check rh-kabi rh-kabi-dup sources-rh
 
@@ -232,11 +270,11 @@ $(REDHAT)/rpm/SOURCES/$(PACKAGE_NAME).spec:
 rh-dist-git-test: export RH_DIST_GIT_TEST="1"
 rh-dist-git-test: rh-dist-git
 
-rh-dist-git: $(REDHAT)/rpm/SOURCES/$(PACKAGE_NAME).spec $(TARBALL) $(KABI_TARBALL)
+rh-dist-git: $(REDHAT)/rpm/SOURCES/$(PACKAGE_NAME).spec $(TARBALL) $(KABI_TARBALL) $(KABIDW_TARBALL)
 ifeq ("$(RHDISTGIT_BRANCH)", "")
  $(error RHDISTGIT_BRANCH unset)
 endif
-	$(REDHAT)/scripts/rh-dist-git.sh "$(RHDISTGIT_BRANCH)" "$(RHDISTGIT_CACHE)" "$(RHDISTGIT_TMP)" "$(RHDISTGIT)" "$(TARBALL)" "$(KABI_TARBALL)" "$(__ZSTREAM)" "$(PACKAGE_NAME)" "$(RHELMAJOR)" "$(RHPKG_BIN)"
+	$(REDHAT)/scripts/rh-dist-git.sh "$(RHDISTGIT_BRANCH)" "$(RHDISTGIT_CACHE)" "$(RHDISTGIT_TMP)" "$(RHDISTGIT)" "$(TARBALL)" "$(KABI_TARBALL)" "$(KABIDW_TARBALL)" "$(__ZSTREAM)" "$(PACKAGE_NAME)" "$(RHELMAJOR)" "$(RHPKG_BIN)"
 
 rh-rtg: rh-release
 	@$(MAKE) rh-release-tag
@@ -331,6 +369,9 @@ rh-full-help:
 	@echo  '                      Requires a pre-compiled tree: run `make rh-configs`, copy the'
 	@echo  '                      relevant config file from redhat/configs/ to .config, run `make`.'
 	@echo  '  rh-check-kabi-dup - Like rh-check-kabi but uses a DUP kABI whitelist.'
+	@echo  '  rh-kabi-dw-base   - Generate the base dataset for kABI DWARF-based check.'
+	@echo  '  rh-kabi-dw-check  - Run DWARF-based kABI comparison of current binaries with the base'
+	@echo  '                      dataset.'
 
 	@echo  ''
 	@echo  'Configuration targets:'
diff --git a/redhat/kernel.spec.template b/redhat/kernel.spec.template
--- a/redhat/kernel.spec.template
+++ b/redhat/kernel.spec.template
@@ -81,6 +81,11 @@ Summary: The Linux kernel
 # Control whether we perform a compat. check against DUP ABI.
 %define with_kabidupchk %{?_with_kabidupchk:  1} %{?!_with_kabidupchk:   0}
 #
+# Control whether to run an extensive DWARF based kABI check.
+# Note that this option needs to have baseline setup in SOURCE300.
+%define with_kabidwchk %{?_without_kabidwchk: 0} %{?!_without_kabidwchk: 1}
+%define with_kabidw_base %{?_with_kabidw_base: 1} %{?!_with_kabidw_base: 0}
+#
 # should we do C=1 builds with sparse
 %define with_sparse    %{?_with_sparse:       1} %{?!_with_sparse:       0}
 #
@@ -100,6 +105,12 @@ Summary: The Linux kernel
 %define with_debug 0
 %define with_kabichk 0
 %define with_kabidupchk 0
+%define with_kabidwchk 0
+%endif
+
+# turn off kABI DWARF-based check if we're generating the base dataset
+%if %{with_kabidw_base}
+%define with_kabidwchk 0
 %endif
 
 %define make_target bzImage
@@ -131,9 +142,10 @@ Summary: The Linux kernel
 %define with_bpftool 0
 %endif
 
-# turn off kABI DUP check if kABI check is disabled
+# turn off kABI DUP check and DWARF-based check if kABI check is disabled
 %if !%{with_kabichk}
 %define with_kabidupchk 0
+%define with_kabidwchk 0
 %endif
 
 %ifnarch noarch
@@ -297,6 +309,9 @@ BuildConflicts: rpm < 4.13.0.1-19
 %global _missing_build_ids_terminate_build 1
 %global _no_recompute_build_ids 1
 %endif
+%if %{with_kabidwchk} || %{with_kabidw_base}
+BuildRequires: kabi-dw
+%endif
 
 %if %{signkernel}%{signmodules}
 BuildRequires: openssl openssl-devel
@@ -368,6 +383,7 @@ Source212: Module.kabi_dup_s390x
 Source213: Module.kabi_dup_x86_64
 
 Source300: kernel-abi-whitelists-%{rpmversion}-%{distro_build}.tar.bz2
+Source301: kernel-kabi-dw-%{rpmversion}-%{distro_build}.tar.bz2
 
 # Sources for kernel-tools
 Source2000: cpupower.service
@@ -581,6 +597,16 @@ AutoReqProv: no
 The kABI package contains information pertaining to the Red Hat Enterprise
 Linux kernel ABI, including lists of kernel symbols that are needed by
 external Linux kernel modules, and a yum plugin to aid enforcement.
+
+%if %{with_kabidw_base}
+%package kabidw-base
+Summary: The baseline dataset for kABI verification using DWARF data
+Group: System Environment/Kernel
+AutoReqProv: no
+%description kabidw-base
+The kabidw-base package contains data describing the current ABI of the Red Hat
+Enterprise Linux kernel, suitable for the kabi-dw tool.
+%endif
 
 #
 # This macro creates a kernel-<subpackage>-debuginfo package.
@@ -1044,6 +1070,54 @@ BuildKernel() {
         rm $RPM_BUILD_ROOT/Module.kabi # for now, don't keep it around.
     else
         echo "**** NOTE: Cannot find DUP reference Module.kabi file. ****"
+    fi
+%endif
+
+%if %{with_kabidw_base}
+    # Don't build kabi base for debug kernels
+    if [ "$Flavour" != "kdump" -a "$Flavour" != "debug" ]; then
+        mkdir -p $RPM_BUILD_ROOT/kabi-dwarf
+        tar xjvf %{SOURCE301} -C $RPM_BUILD_ROOT/kabi-dwarf
+
+        mkdir -p $RPM_BUILD_ROOT/kabi-dwarf/whitelists
+        tar xjvf %{SOURCE300} -C $RPM_BUILD_ROOT/kabi-dwarf/whitelists
+
+        echo "**** GENERATING DWARF-based kABI baseline dataset ****"
+        chmod 0755 $RPM_BUILD_ROOT/kabi-dwarf/run_kabi-dw.sh
+        $RPM_BUILD_ROOT/kabi-dwarf/run_kabi-dw.sh generate \
+            "$RPM_BUILD_ROOT/kabi-dwarf/whitelists/kabi-current/kabi_whitelist_%{_target_cpu}" \
+            "$(pwd)" \
+            "$RPM_BUILD_ROOT/kabidw-base/%{_target_cpu}${Flavour:+.${Flavour}}" || :
+
+        rm -rf $RPM_BUILD_ROOT/kabi-dwarf
+    fi
+%endif
+
+%if %{with_kabidwchk}
+    if [ "$Flavour" != "kdump" ]; then
+        mkdir -p $RPM_BUILD_ROOT/kabi-dwarf
+        tar xjvf %{SOURCE301} -C $RPM_BUILD_ROOT/kabi-dwarf
+        if [ -d "$RPM_BUILD_ROOT/kabi-dwarf/base/%{_target_cpu}${Flavour:+.${Flavour}}" ]; then
+            mkdir -p $RPM_BUILD_ROOT/kabi-dwarf/whitelists
+            tar xjvf %{SOURCE300} -C $RPM_BUILD_ROOT/kabi-dwarf/whitelists
+
+            echo "**** GENERATING DWARF-based kABI dataset ****"
+            chmod 0755 $RPM_BUILD_ROOT/kabi-dwarf/run_kabi-dw.sh
+            $RPM_BUILD_ROOT/kabi-dwarf/run_kabi-dw.sh generate \
+                "$RPM_BUILD_ROOT/kabi-dwarf/whitelists/kabi-current/kabi_whitelist_%{_target_cpu}" \
+                "$(pwd)" \
+                "$RPM_BUILD_ROOT/kabi-dwarf/base/%{_target_cpu}${Flavour:+.${Flavour}}.tmp" || :
+
+            echo "**** kABI DWARF-based comparison report ****"
+            $RPM_BUILD_ROOT/kabi-dwarf/run_kabi-dw.sh compare \
+                "$RPM_BUILD_ROOT/kabi-dwarf/base/%{_target_cpu}${Flavour:+.${Flavour}}" \
+                "$RPM_BUILD_ROOT/kabi-dwarf/base/%{_target_cpu}${Flavour:+.${Flavour}}.tmp" || :
+            echo "**** End of kABI DWARF-based comparison report ****"
+        else
+            echo "**** Baseline dataset for kABI DWARF-BASED comparison report not found ****"
+        fi
+
+        rm -rf $RPM_BUILD_ROOT/kabi-dwarf
     fi
 %endif
 
@@ -1697,6 +1771,14 @@ fi
 %files -n kernel-abi-whitelists
 %defattr(-,root,root,-)
 /lib/modules/kabi-*
+%endif
+
+%if %{with_kabidw_base}
+%ifarch x86_64 s390x ppc64 ppc64le aarch64
+%files kabidw-base
+%defattr(-,root,root)
+/kabidw-base/%{_target_cpu}/*
+%endif
 %endif
 
 %if %{with_perf}
