[redhat] fix make rhg-brew
Message-id: <ab28ad9bab48071a8c5bf3f2eb1eb6ec27d29266.1537546121.git.jbenc@redhat.com>
Patchwork-id: 229076
O-Subject: [RHEL8] redhat: fix make rhg-brew
Bugzilla:
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Paolo Abeni <pabeni@redhat.com>

Bugzilla: INTERNAL
Brew: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=18444067
Upstream status: RHEL-only

The Python scripts that are part of our tooling should use
/usr/libexec/platform-python, not /usr/bin/python3, as /usr/bin/python3 is
user configurable and can point to whatever Python 3 version. In the brew
environment, /usr/bin/python3 is not even available.

Change the show-kabi shebang to /usr/libexec/platform-python. This however
breaks 'make rh-brew' on older systems (such as RHEL7 with Python 3 from
EPEL). Provide a meaningful error message to the user with instruction how
to fix that and be able to continue building on the older system.

Signed-off-by: Jiri Benc <jbenc@redhat.com>
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

diff --git a/redhat/Makefile b/redhat/Makefile
--- a/redhat/Makefile
+++ b/redhat/Makefile
@@ -47,7 +47,19 @@ include Makefile.cross
 
 default: rh-help
 
-rh-kabi:
+rh-python-check:
+	@if [ ! -f /usr/libexec/platform-python ]; then \
+		if ! which python3 > /dev/null 2>&1; then \
+			echo "ERROR: Python 3 is needed." ; \
+			exit 1; \
+		fi; \
+		echo "ERROR: your build environment is not compatible with RHEL8."; \
+		echo "To fix this, run:"; \
+		echo "ln -s `which python3` /usr/libexec/platform-python"; \
+		exit 1; \
+	fi
+
+rh-kabi: rh-python-check
 	@for KABIARCH in $(ARCH_LIST); do \
 		$(REDHAT)/kabi/show-kabi -k $(REDHAT)/kabi/kabi-module/ -m \
 			-a $$KABIARCH -r $(RHELMAJOR).$(RHELMINOR) > $(REDHAT)/kabi/Module.kabi_$$KABIARCH;\
@@ -59,7 +71,7 @@ rh-kabi:
 	done;
 	@(cd $(REDHAT)/kabi/ && ln -Tsf kabi-rhel$(RHELMAJOR)$(RHELMINOR) kabi-current)
 
-rh-kabi-dup:
+rh-kabi-dup: rh-python-check
 	@for KABIARCH in $(ARCH_LIST); do \
 		touch $(REDHAT)/kabi/Module.kabi_dup_$$KABIARCH;\
 		if [ -d $(REDHAT)/kabi/kabi-dup-module/kabi_$$KABIARCH ]; then \
