[redhat] genspec.sh: Do not reflect changes to redhat/rhdocs to end users
Message-id: <20190318162401.25763-1-dzickus@redhat.com>
Patchwork-id: 246878
O-Subject: [RHEL8 PATCH 2/2 V4] redhat/genspec.sh: Do not reflect changes to redhat/rhdocs to end users
Bugzilla:
RH-Acked-by: Prarit Bhargava <prarit@redhat.com>
RH-Acked-by: Jakub Racek <jracek@redhat.com>

From: Prarit Bhargava <prarit@redhat.com>

Changes in redhat/rhdocs should not be reported to users.  Blacklist
the directory so changes are not refected in the rpm changelog.

V2: Add git version check to prevent older version from corrupting changelog
    Tweaked the pathspec magic (Herton)
V3: Reworked the git check logic (Jiri B.)
V4: Refresh on latest HEAD (Herton)

Signed-off-by: Prarit Bhargava <prarit@redhat.com>
Signed-off-by: Don Zickus <dzickus@redhat.com>

Cc: Don Zickus <dzickus@redhat.com>
Cc: Herton R. Krzesinski <herton@redhat.com>
Cc: jtoppins@redhat.com
Cc: jracek@redhat.com
Signed-off-by: Herton R. Krzesinski <herton@redhat.com>

diff --git a/redhat/Makefile b/redhat/Makefile
--- a/redhat/Makefile
+++ b/redhat/Makefile
@@ -181,7 +181,18 @@ $(KABIDW_TARBALL):
 	fi
 	@(cd kabi-dwarf && tar cjvf $(SOURCES)/$(KABIDW_TARFILE) base run_kabi-dw.sh)
 
-setup-source: rh-clean-sources
+
+rh-git-version-check:
+	@# genspec.sh uses pathspec magic that wasn't introduced until version 2.13
+	@IFS=" ."; \
+	set -- $$(git --version); \
+	IFS=; \
+	if [ "$$3" -lt 2 -o \( "$$3" -eq 2 -a "$$4" -lt 13 \) ]; then \
+		echo "ERROR: You need git version 2.13 or newer to run some setup commands"; \
+		exit 1; \
+	fi
+
+setup-source: rh-git-version-check rh-clean-sources
 	@cp $(REDHAT)/$(SPECFILE).template $(SOURCES)/$(SPECFILE)
 	@if [ ! -e  $(REDHAT)/$(CHANGELOG) ]; then \
 		echo "Creating $(CHANGELOG) as copy of $(CHANGELOG_PREV)"; \
